/* 两个列表:分别是Components 和 apis */
export const ComponentsList = [
    {
        title:'<text>',
        icon:'logo-angular',
        componentName: 'text'
    },
    {
        title:'<textInput>',
        icon:'ios-paper-plane',
        componentName:'textInput'
    },
    {
        title:'<transfrom>',
        icon:'ios-paw-outline',
        componentName:'transform'
    },
    {
        title:'<view>',
        icon:'ios-nuclear-outline',
        componentName:'view'
    },
    {
        title:'<animate>',
        icon:'ios-paw-outline',
        componentName:'animate'
    },
    {
        title:'<modal>',
        icon:'logo-angular',
        componentName:'modal'
    },
    {
        title:'<StatusBar>',
        icon:'logo-angular',
        componentName:'statusbar'
    },
    {
        title:'<switch>',
        icon:'logo-angular',
        componentName:'switch'
    },
    {
        title:'<layoutEvent>',
        icon:'logo-angular',
        componentName:'layoutEvent'
    },
    {
        title:'<scrollview>',
        icon:'logo-angular',
        componentName:'scrollview'
    },
    {
        title:'<listview>',
        icon:'logo-angular',
        componentName:'listview'
    },
    {
        title:'<listview-grid>',
        icon:'logo-angular',
        componentName:'listgrid'
    },
    {
        title:'<listview-paging>',
        icon:'logo-angular',
        componentName:'listpaging'
    },
    {
        title:'<scrollview>',
        icon:'logo-angular',
        componentName:'scrollview'
    },
    {
        title:'<swiper-listview>',
        icon:'logo-angular',
        componentName:'swiperListview'
    },
];
export const ApisList = [
    {
        title:'<text>',
        icon:'logo-angular',
        componentName: 'text'
    },
    {
        title:'<textInput>',
        icon:'ios-paper-plane',
        componentName:'textInput'
    },
    {
        title:'<transfrom>',
        icon:'ios-paw-outline',
        componentName:'transform'
    },
    {
        title:'<view>',
        icon:'ios-nuclear-outline',
        componentName:'view'
    },
    {
        title:'text',
        icon:'logo-angular'
    },
    {
        title:'text',
        icon:'logo-angular'
    },
    {
        title:'text',
        icon:'logo-angular'
    },
    {
        title:'text',
        icon:'logo-angular'
    },
    {
        title:'text',
        icon:'logo-angular'
    },
    {
        title:'text',
        icon:'logo-angular'
    }
];