# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'tapp' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  #
 

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
   ]

  # Pods for tapp

  target 'tappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tappUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
